# 1. Dataset

### Use the California Housing Dataset from Scikit-Learn.

In [96]:
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()

### Convert into DataFrame.

In [97]:
import pandas as pd

df = pd.DataFrame(housing.data, columns = housing.feature_names)
df["Price"] = housing.target

df.to_csv("california_housing.csv", index = False)

df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

# 2. Explore Dataset

In [98]:
df.shape
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
 8   Price       20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
Price         0
dtype: int64

# 3. Train/Test Split

In [99]:
from sklearn.model_selection import train_test_split

X = df.drop("Price", axis = 1)
y = df["Price"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 42
)

print("Training Features:", X_train.shape)
print("Testing Features:", X_test.shape)
print("Training Labels:", y_train.shape)
print("Testing Labels:", y_test.shape)

Training Features: (16512, 8)
Testing Features: (4128, 8)
Training Labels: (16512,)
Testing Labels: (4128,)

# 4. Train Model

In [100]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

# 5. Make Predictions

In [101]:
predictions = model.predict(X_test)

predictions[:10]

array([0.71912284, 1.76401657, 2.70965883, 2.83892593, 2.60465725,
       2.01175367, 2.64550005, 2.16875532, 2.74074644, 3.91561473])

# 6.Evaluate Model

In [102]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

print(mean_absolute_error(y_test, predictions))
print(mean_squared_error(y_test, predictions))
print(r2_score(y_test, predictions))

0.5332001304956564
0.555891598695244
0.5757877060324511

# 7. Interpret Coefficients

In [103]:
coef = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
})

coef.sort_values(by = "Coefficient")

      Feature  Coefficient
7   Longitude    -0.433708
6    Latitude    -0.419792
2    AveRooms    -0.123323
5    AveOccup    -0.003526
4  Population    -0.000002
1    HouseAge     0.009724
0      MedInc     0.448675
3   AveBedrms     0.783145